name: CD
on:
  push:
    branches:
      - master
jobs:

  deploy:
    name: runner / deploy
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Setup Google Cloud
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: GAE Deploy
        uses: actions/gcloud/cli@master
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.PROJECT_ID }}
        with:
          args: app deploy --quiet
