name: Deploy
on:
  push:
    branches:
      - master
jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Setup Google Cloud
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: GAE Deploy
        uses: actions/gcloud/cli@master
        with:
          args: app deploy --project=${{ secrets.PROJECT_ID }} --quiet
